INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Russia league', '7', 'RU', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Russian Cup', '311', 'RU', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Russian Super Cup', '212', 'RU', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Premier League', '2', 'EN', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Championship', '77', 'EN', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Community Shield', '149', 'EN', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('FA Cup', '152', 'EN', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('FA Trophy', '153', 'EN', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Serie A', '4', 'IT', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Coppa Italia', '179', 'IT', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Super Cup', '178', 'IT', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Ligue 1', '5', 'FR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Cup', '162', 'FR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Super Cup', '160', 'FR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('League Cup', '163', 'FR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Bundesliga', '1', 'DE', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('DFB Cup', '167', 'DE', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Germany Super Cup', '169', 'DE', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('MLS', '76', 'US', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('US Open Cup', '118', 'US', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('NASL', '382', 'US', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('United Soccer League', '383', 'US', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Primeira Liga', '8', 'PT', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Portugal Cup', '212', 'PT', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Portugal Super Cup', '211', 'PT', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Copa MX', '117', 'MX', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Liga MX', '45', 'MX', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Supercopa MX', '296', 'MX', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Primera Division', '23', 'AR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Copa Argentina', '230', 'AR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Super Cup', '236', 'AR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Serie A', '24', 'BR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Copa Do Brasil', '256', 'BR', true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('FIFA World Cup', '362', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('FIFA Confederations Cup', '270', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('FIFA Club World Cup', '372', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Champions League', '244', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('Europa League', '245', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('UEFA EURO Qualification', '274', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('UEFA Nations League', '350', null, true, NOW(), NOW());
INSERT INTO tournaments (name, ls_id, country, is_active, created_at, updated_at) VALUES ('World Cup UEFA Qualifiers', '363', null, true, NOW(), NOW());
